---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: YWRtaW4=
  password: MTIz

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
type: Opaque
data:
  mduser: YWRtaW4=
  mdpass: MTIz
  meuser: YWRtaW4=
  mepass: MTIz